#!/usr/bin/perl

use warnings;
use strict;

use feature qw/say/;

use DigitalOcean;
use File::Slurp qw/read_file/;
use FindBin;
use List::Util qw/all/;


my %conf;
my @signals = qw/INT HUP TERM QUIT/;

foreach(read_file("$FindBin::Bin/config")) {
   chomp;
   if (m/\A\h*+([^\h]++)\h*+=\h*+([^\h]++)\h*+\z/) {
      $conf{$1} = $2
   }
}

if (@ARGV) {
   if ($ARGV[0] eq 'i' || $ARGV[0] eq '-i' || $ARGV[0] eq 'interactive' || $ARGV[0] eq '--interactive') {
      $conf{interactive} = 1
   } else {
      $conf{interactive} = 0
   }
}

my $do = DigitalOcean->new(client_id=> $conf{client_id}, api_key => $conf{api_key}, wait_on_events => 1);
 

my $vpn_droplet;
my @droplets = @{$do->droplets};

if (@droplets) {
   foreach (@droplets) {
      if ($_->name eq $conf{name}) {
         $vpn_droplet = $_
      }
   }
}

sub create_droplet
{
   say "Creating Droplet " . $_[1]->{name};
   my $d = $_[0]->create_droplet(
      name      => $_[1]->{name},
      size_id   => $_[1]->{size_id},
      image_id  => $_[1]->{image_id},
      region_id => $_[1]->{region_id}
   );
   say "Droplet Id: " . $d->id;

   $d
}

sub destroy_droplet
{
   my $droplet;
   if (@_) {
      if (all { $_[0] ne $_ } @signals) {
         $droplet = $_[0]
      } else {
         if ($vpn_droplet) {
            $droplet = $vpn_droplet
         } else {
            die "Can't destroy droplet\n"
         }
      }
   }
   say "Destroying Droplet " . $droplet->name;
   say "Droplet id: " . $droplet->id;

   $droplet->destroy;

   undef
}


unless ($vpn_droplet) {
   if ($conf{interactive}) {
      say "Interactive mode";
      foreach (@signals) {
         $SIG{$_} = \&destroy_droplet
      }
   }

   $vpn_droplet = create_droplet $do, \%conf;

   if ($conf{interactive}) {
      say "Waiting for signal ...";
      sleep
   }
} else {
   destroy_droplet $vpn_droplet;
}

say "Done.";


